spring:
  profiles:
    active: dev

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration



  mail:
    host: ${MAIL_HOST:localhost} # The ':localhost' is a fallback default
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:default}
    password: ${MAIL_PASSWORD:default}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 900000
      refresh-token:
        expiration: 3_600_000



#Data Initialization
admin:
  email: niiggaa786958@gmail.com
  password: Admin@123
  name: Manish Singh
  phone: +918953749908
